import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#0f1418',
        'surface-dim': '#0f1418',
        'surface-bright': '#353a3e',
        'surface-container-lowest': '#0a0f13',
        'surface-container-low': '#171c20',
        'surface-container': '#1b2024',
        'surface-container-high': '#252b2f',
        'surface-container-highest': '#30353a',
        'on-surface': '#dee3e9',
        'on-surface-variant': '#bec8d2',
        'outline': '#88929b',
        'outline-variant': '#3e4850',
        'primary': '#89ceff',
        'on-primary': '#00344d',
        'primary-container': '#0ea5e9',
        'secondary': '#4edea3',
        'on-secondary': '#003824',
        'tertiary': '#ffb95f',
        'on-tertiary': '#472a00',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#0f1418',
        'on-background': '#dee3e9',
        'surface-variant': '#30353a',
        'surface-tint': '#89ceff',
        'secondary-container': '#00a572',
        'tertiary-container': '#d88a00',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '450' }],
        'code-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      spacing: {
        'sidebar': '260px',
        'base': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '20px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
export default config
