LICENSE_ACCEPTED=TRUE
COMMON_DEFAULTS_ENABLED=yes
INSTALL_PACKAGES="zimbra-core zimbra-ldap zimbra-logger zimbra-mta zimbra-snmp zimbra-store zimbra-apache zimbra-spell zimbra-memcached zimbra-proxy"

# Global Config
HOSTNAME=mail.mailos.local
CREATE_DOMAIN=yes
ZIMBRA_DOMAIN=mailos.local
TIMEZONE=Europe/Istanbul

# Admin
ADMIN_ACCOUNT_NAME=admin@mailos.local
ZIMBRA_STORE_ADMIN_PASSWORD=ZimbraAdmin2024!

# LDAP
LDAP_MASTER_PASSWORD=ZimbraLdap2024!
LDAP_ROOT_PASSWORD=ZimbraLdap2024!
LDAP_REPLICATION_PASSWORD=ZimbraLdap2024!
LDAP_NGINX_PASSWORD=ZimbraLdap2024!
LDAP_AMAVIS_PASSWORD=ZimbraLdap2024!
LDAP_POSTFIX_PASSWORD=ZimbraLdap2024!

# Ports
ZIMBRA_HTTP_PROXY_PORT=8080
ZIMBRA_HTTPS_PROXY_PORT=8443
ZIMBRA_ADMIN_PROXY_PORT=9071
ZIMBRA_ADMIN_CONSOLE_PORT=7071
